apiVersion: apps/v1
kind: Deployment
metadata:
  name: ajay3
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ajay
  template:
    metadata:
      labels:
        app: ajay
    spec:
      containers:
      - name: ajay
        image: nginx
        ports:
        - containerPort: 80
