apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: pythonv1-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pythonv1
  minReplicas: 5
  maxReplicas: 20
  targetCPUUtilizationPercentage: 60

