apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: avengers-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      type: local

