apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-suite
spec:
  replicas: 2
  selector:
    matchLabels:
      app: llm-suite
  template:
    metadata:
      labels:
        app: llm-suite
    spec:
      containers:
      - name: llm-suite
        image: your-dockerhub-username/llm-suite:latest
        ports:
        - containerPort: 5000
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: llm-suite-service
spec:
  selector:
    app: llm-suite
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  - protocol: TCP
    port: 81
    targetPort: 3000
  type: LoadBalancer